//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.288.
// 
namespace Metreos.Common.Mec 
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ConferenceCommand.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("conferenceRequest", Namespace="http://tempuri.org/ConferenceCommand.xsd", IsNullable=false)]
    public class conferenceRequestType 
    {
        
        /// <remarks/>
        public string startTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("location", IsNullable=true)]
        public locationType[] location;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public conferenceRequestTypeType type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ConferenceCommand.xsd")]
    public class locationType 
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool muted;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mutedSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ConferenceCommand.xsd")]
    public enum conferenceRequestTypeType 
    {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        terminate,
        
        /// <remarks/>
        join,
        
        /// <remarks/>
        mute,
        
        /// <remarks/>
        kick,
        
        /// <remarks/>
        isConferenceActive,
        
        /// <remarks/>
        isLocationOnline,
    }
}
