//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.3705.288.
// 
namespace Metreos.Common.Mec
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Response.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("conferenceResponse", Namespace="http://tempuri.org/Response.xsd", IsNullable=false)]
    public class conferenceResponseType 
    {
        
        /// <remarks/>
        public resultType result;
        
        /// <remarks/>
        public string conferenceId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locationId")]
        public locationIdType[] locationId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public typeType type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Response.xsd")]
    public enum resultType 
    {
        
        /// <remarks/>
        success,
        
        /// <remarks/>
        failure,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Response.xsd")]
    public class locationIdType 
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Response.xsd")]
    public enum typeType 
    {
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        terminate,
        
        /// <remarks/>
        join,
        
        /// <remarks/>
        mute,
        
        /// <remarks/>
        kick,
        
        /// <remarks/>
        isConferenceActive,
        
        /// <remarks/>
        isLocationOnline,
    }
}
