//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace Metreos.PackageGeneratorCore.PackageXml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("package", Namespace="http://metreos.com/ActionEventPackage.xsd", IsNullable=false)]
    public class packageType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable=false)]
        public actionType[] actionList;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("event", IsNullable=false)]
        public eventType[] eventList;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public class actionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actionParam")]
        public actionParamType[] actionParam;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultData")]
        public resultDataType[] resultData;
        
        /// <remarks/>
        public returnValueType returnValue;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("asyncCallback")]
        public string[] asyncCallback;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("icon")]
        public iconType[] icon;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public actionTypeType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowCustomParams;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool final;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public class actionParamType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnumItem")]
        public string[] EnumItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public useType use;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowMultiple;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string defaultValue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public enum useType {
        
        /// <remarks/>
        required,
        
        /// <remarks/>
        optional,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public class eventParamType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnumItem")]
        public string[] EnumItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool guaranteed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public class eventType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventParam")]
        public eventParamType[] eventParam;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("icon")]
        public iconType[] icon;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public eventTypeType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expects;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public class iconType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public iconTypeType type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public enum iconTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16x16x8")]
        Item16x16x8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16x16x32")]
        Item16x16x32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32x32x8")]
        Item32x32x8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32x32x32")]
        Item32x32x32,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public enum eventTypeType {
        
        /// <remarks/>
        triggering,
        
        /// <remarks/>
        nontriggering,
        
        /// <remarks/>
        hybrid,
        
        /// <remarks/>
        asyncCallback,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public class returnValueType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnumItem")]
        public string[] EnumItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public class resultDataType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/ActionEventPackage.xsd")]
    public enum actionTypeType {
        
        /// <remarks/>
        provider,
        
        /// <remarks/>
        native,
        
        /// <remarks/>
        appControl,
    }
}
