//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace Metreos.PackageGeneratorCore.PackageXml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/NativeTypePackage.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("nativeTypePackage", Namespace="http://metreos.com/NativeTypePackage.xsd", IsNullable=false)]
    public class nativeTypePackageType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public typeType[] type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/NativeTypePackage.xsd")]
    public class typeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputType")]
        public parameterType[] inputType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("indexer")]
        public indexerType[] indexer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customProperty")]
        public customPropertyType[] customProperty;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customMethod")]
        public customMethodType[] customMethod;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool serializable;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/NativeTypePackage.xsd")]
    public class parameterType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/NativeTypePackage.xsd")]
    public class customMethodType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public parameterType[] parameter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/NativeTypePackage.xsd")]
    public class customPropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/NativeTypePackage.xsd")]
    public class indexerType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string indexType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description;
    }
}
