//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace Metreos.Types.CiscoIpPhone {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneMenu", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneMenuType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public CiscoIPPhoneMenuItemType[] MenuItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneMenuItemType {
        
        /// <remarks/>
        public System.UInt16 IconIndex;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IconIndexSpecified;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string URL;
        
        /// <remarks/>
        public CiscoIPPhoneTouchAreaType TouchArea;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneTouchAreaType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short X1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short Y1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short X2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short Y2;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneSoftKeyType {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string URL;

        /// <remarks/>
        public string URLDown;
        
        /// <remarks/>
        public System.UInt16 Position;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneImage", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneImageType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        public short LocationX;
        
        /// <remarks/>
        public short LocationY;
        
        /// <remarks/>
        public System.UInt16 Width;
        
        /// <remarks/>
        public System.UInt16 Height;
        
        /// <remarks/>
        public System.UInt16 Depth;
        
        /// <remarks/>
        public string Data;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneStatus", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneStatusType {
        
        /// <remarks/>
        public string Text;
        
        /// <remarks/>
        public short Timer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimerSpecified;
        
        /// <remarks/>
        public short LocationX;
        
        /// <remarks/>
        public short LocationY;
        
        /// <remarks/>
        public System.UInt16 Width;
        
        /// <remarks/>
        public System.UInt16 Height;
        
        /// <remarks/>
        public System.UInt16 Depth;
        
        /// <remarks/>
        public string Data;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneIconMenu", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneIconMenuType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public CiscoIPPhoneMenuItemType[] MenuItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IconItem")]
        public CiscoIPPhoneIconItemType[] IconItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneIconItemType {
        
        /// <remarks/>
        public System.UInt16 Index;
        
        /// <remarks/>
        public System.UInt16 Width;
        
        /// <remarks/>
        public System.UInt16 Height;
        
        /// <remarks/>
        public System.UInt16 Depth;
        
        /// <remarks/>
        public string Data;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneDirectory", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneDirectoryType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DirectoryEntry")]
        public CiscoIPPhoneDirectoryEntryType[] DirectoryEntry;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneDirectoryEntryType {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Telephone;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneGraphicMenu", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneGraphicMenuType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        public short LocationX;
        
        /// <remarks/>
        public short LocationY;
        
        /// <remarks/>
        public System.UInt16 Width;
        
        /// <remarks/>
        public System.UInt16 Height;
        
        /// <remarks/>
        public System.UInt16 Depth;
        
        /// <remarks/>
        public string Data;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public CiscoIPPhoneMenuItemType[] MenuItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneInput", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneInputType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        public string URL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InputItem")]
        public CiscoIPPhoneInputItemType[] InputItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneInputItemType {
        
        /// <remarks/>
        public string DisplayName;
        
        /// <remarks/>
        public string QueryStringParam;
        
        /// <remarks/>
        public string InputFlags;
        
        /// <remarks/>
        public string DefaultValue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneText", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneTextType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        public string Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneExecute", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneExecuteType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExecuteItem")]
        public CiscoIPPhoneExecuteItemType[] ExecuteItem;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneExecuteItemType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.UInt16 Priority;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneError", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneErrorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short Number;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneResponse", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneResponseType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseItem")]
        public CiscoIPPhoneResponseItemType[] ResponseItem;
    }
    
    /// <remarks/>
    public class CiscoIPPhoneResponseItemType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Data;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URL;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneImageFile", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneImageFileType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        public short LocationX;
        
        /// <remarks/>
        public short LocationY;
        
        /// <remarks/>
        public string URL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneStatusFile", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneStatusFileType {
        
        /// <remarks/>
        public string Text;
        
        /// <remarks/>
        public short Timer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimerSpecified;
        
        /// <remarks/>
        public short LocationX;
        
        /// <remarks/>
        public short LocationY;
        
        /// <remarks/>
        public string URL;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneGraphicFileMenu", Namespace="", IsNullable=false)]
    public class CiscoIPPhoneGraphicFileMenuType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Prompt;
        
        /// <remarks/>
        public string URL;
        
        /// <remarks/>
        public short LocationX;
        
        /// <remarks/>
        public short LocationY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public CiscoIPPhoneMenuItemType[] MenuItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public CiscoIPPhoneSoftKeyType[] SoftKeyItem;
    }
}
