//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace Metreos.Samoa.FunctionalTestFramework {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestSettings.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TestSettings.xsd", IsNullable=false)]
    public class TestSettings {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tests")]
        public testType[] tests;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestSettings.xsd")]
    public class testType {
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool success = false;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables")]
        public variableType[] variables;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/TestSettings.xsd")]
    public class variableType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
}
