//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Net;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


namespace Metreos.Common.Reserve
{
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BoRecordSoapBinding", Namespace="urn:BoRecord")]
    public class BoRecordActionsInterfaceService : System.Web.Services.Protocols.SoapHttpClientProtocol 
    {
        public void SetUrl(string ip)
        {
            SetUrl(ip, null, null, false);
        }

//        protected override System.Net.WebResponse GetWebResponse(System.Net.WebRequest request)
//        {
//            System.Net.HttpWebResponse response = base.GetWebResponse (request) as System.Net.HttpWebResponse;
//            System.IO.Stream stream = response.GetResponseStream();
// 
//            byte[] buffer = new byte[2048];
//            System.IO.MemoryStream data = new System.IO.MemoryStream(2048);
//            
//            int n = 0;
//            int bytesRead = 0;
//
//            while (true) 
//            {
//                n = stream.Read(buffer, 0, buffer.Length);
//                if (n == 0) break;
//        
//                data.Write(buffer, 0, n);
//                bytesRead += n;
//            }
//
//
//            using(System.IO.FileStream file = System.IO.File.Open("test.xml", System.IO.FileMode.Create))
//            {
//                data.WriteTo(file);
//            }
//
//            stream.Seek(0, System.IO.SeekOrigin.Begin);
//            return response;
//        }

        public void SetUrl(string ip, string port, string proxyUrl, bool secure)
        {
            if(proxyUrl != null)
            {
                this.Proxy = new WebProxy(proxyUrl);
            }
            this.Url = String.Format("http{2}://{0}:{1}/services/BoRecord", ip, port == null ? "8001" : port, secure ? "s" : String.Empty);
        }
    
        /// <remarks/>
        public BoRecordActionsInterfaceService() 
        {
            this.Url = "http://app1env51.prd.tririga.net:8001/services/BoRecord";
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoSectionCounts", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBoRecordSectionCountsReturn")]
        public string getBoRecordSectionCounts(string securityToken, long userId, long recordId) 
        {
            object[] results = this.Invoke("getBoRecordSectionCounts", new object[] {
                                                                                        securityToken,
                                                                                        userId,
                                                                                        recordId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetBoRecordSectionCounts(string securityToken, long userId, long recordId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getBoRecordSectionCounts", new object[] {
                                                                                 securityToken,
                                                                                 userId,
                                                                                 recordId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetBoRecordSectionCounts(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBoRecordReturn")]
        public string getBoRecord(string securityToken, long userId, long companyId, long recordId) 
        {
            object[] results = this.Invoke("getBoRecord", new object[] {
                                                                           securityToken,
                                                                           userId,
                                                                           companyId,
                                                                           recordId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetBoRecord(string securityToken, long userId, long companyId, long recordId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getBoRecord", new object[] {
                                                                    securityToken,
                                                                    userId,
                                                                    companyId,
                                                                    recordId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetBoRecord(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getFullBoRecordReturn")]
        public string getFullBoRecord(string securityToken, long userId, long companyId, long recordId) 
        {
            object[] results = this.Invoke("getFullBoRecord", new object[] {
                                                                               securityToken,
                                                                               userId,
                                                                               companyId,
                                                                               recordId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetFullBoRecord(string securityToken, long userId, long companyId, long recordId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getFullBoRecord", new object[] {
                                                                        securityToken,
                                                                        userId,
                                                                        companyId,
                                                                        recordId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetFullBoRecord(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSimpleBoStructureReturn")]
        public string getSimpleBoStructure(string securityToken, long userId, long companyId, int moduleId, long boId) 
        {
            object[] results = this.Invoke("getSimpleBoStructure", new object[] {
                                                                                    securityToken,
                                                                                    userId,
                                                                                    companyId,
                                                                                    moduleId,
                                                                                    boId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetSimpleBoStructure(string securityToken, long userId, long companyId, int moduleId, long boId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getSimpleBoStructure", new object[] {
                                                                             securityToken,
                                                                             userId,
                                                                             companyId,
                                                                             moduleId,
                                                                             boId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetSimpleBoStructure(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBoStructureReturn")]
        public string getBoStructure(string securityToken, long userId, long companyId, int moduleId, long boId) 
        {
            object[] results = this.Invoke("getBoStructure", new object[] {
                                                                              securityToken,
                                                                              userId,
                                                                              companyId,
                                                                              moduleId,
                                                                              boId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetBoStructure(string securityToken, long userId, long companyId, int moduleId, long boId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getBoStructure", new object[] {
                                                                       securityToken,
                                                                       userId,
                                                                       companyId,
                                                                       moduleId,
                                                                       boId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetBoStructure(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("saveBoRecordReturn")]
        public string saveBoRecord(string securityToken, long userId, long companyId, string dataXML) 
        {
            object[] results = this.Invoke("saveBoRecord", new object[] {
                                                                            securityToken,
                                                                            userId,
                                                                            companyId,
                                                                            dataXML});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginsaveBoRecord(string securityToken, long userId, long companyId, string dataXML, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("saveBoRecord", new object[] {
                                                                     securityToken,
                                                                     userId,
                                                                     companyId,
                                                                     dataXML}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndsaveBoRecord(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("saveBoRecordIntegrationReturn")]
        public string saveBoRecordIntegration(string securityToken, long userId, long companyId, string dataXML) 
        {
            object[] results = this.Invoke("saveBoRecordIntegration", new object[] {
                                                                                       securityToken,
                                                                                       userId,
                                                                                       companyId,
                                                                                       dataXML});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginsaveBoRecordIntegration(string securityToken, long userId, long companyId, string dataXML, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("saveBoRecordIntegration", new object[] {
                                                                                securityToken,
                                                                                userId,
                                                                                companyId,
                                                                                dataXML}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndsaveBoRecordIntegration(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("deleteRecordFromSectionReturn")]
        public string deleteRecordFromSection(string securityToken, long userId, long companyId, string sectionName, long recordId, long sectionRecordId) 
        {
            object[] results = this.Invoke("deleteRecordFromSection", new object[] {
                                                                                       securityToken,
                                                                                       userId,
                                                                                       companyId,
                                                                                       sectionName,
                                                                                       recordId,
                                                                                       sectionRecordId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegindeleteRecordFromSection(string securityToken, long userId, long companyId, string sectionName, long recordId, long sectionRecordId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("deleteRecordFromSection", new object[] {
                                                                                securityToken,
                                                                                userId,
                                                                                companyId,
                                                                                sectionName,
                                                                                recordId,
                                                                                sectionRecordId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EnddeleteRecordFromSection(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBoInitialActionsReturn")]
        public string getBoInitialActions(string securityToken, long userId, long companyId, long boId) 
        {
            object[] results = this.Invoke("getBoInitialActions", new object[] {
                                                                                   securityToken,
                                                                                   userId,
                                                                                   companyId,
                                                                                   boId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetBoInitialActions(string securityToken, long userId, long companyId, long boId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getBoInitialActions", new object[] {
                                                                            securityToken,
                                                                            userId,
                                                                            companyId,
                                                                            boId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetBoInitialActions(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBoRecordActionsReturn")]
        public string getBoRecordActions(string securityToken, long userId, long companyId, long boId, long recordId) 
        {
            object[] results = this.Invoke("getBoRecordActions", new object[] {
                                                                                  securityToken,
                                                                                  userId,
                                                                                  companyId,
                                                                                  boId,
                                                                                  recordId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetBoRecordActions(string securityToken, long userId, long companyId, long boId, long recordId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getBoRecordActions", new object[] {
                                                                           securityToken,
                                                                           userId,
                                                                           companyId,
                                                                           boId,
                                                                           recordId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetBoRecordActions(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("doBoRecordActionReturn")]
        public string doBoRecordAction(string securityToken, long userId, long companyId, long recordId, long boId, string actionName, string label, long boActionLabelId) 
        {
            object[] results = this.Invoke("doBoRecordAction", new object[] {
                                                                                securityToken,
                                                                                userId,
                                                                                companyId,
                                                                                recordId,
                                                                                boId,
                                                                                actionName,
                                                                                label,
                                                                                boActionLabelId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegindoBoRecordAction(string securityToken, long userId, long companyId, long recordId, long boId, string actionName, string label, long boActionLabelId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("doBoRecordAction", new object[] {
                                                                         securityToken,
                                                                         userId,
                                                                         companyId,
                                                                         recordId,
                                                                         boId,
                                                                         actionName,
                                                                         label,
                                                                         boActionLabelId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EnddoBoRecordAction(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("addConversionRatesReturn")]
        public string addConversionRates(string securityToken, long userId, string dataXML) 
        {
            object[] results = this.Invoke("addConversionRates", new object[] {
                                                                                  securityToken,
                                                                                  userId,
                                                                                  dataXML});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginaddConversionRates(string securityToken, long userId, string dataXML, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("addConversionRates", new object[] {
                                                                           securityToken,
                                                                           userId,
                                                                           dataXML}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndaddConversionRates(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateConversionRatesEnddateReturn")]
        public string updateConversionRatesEnddate(string securityToken, long userId, string dataXML) 
        {
            object[] results = this.Invoke("updateConversionRatesEnddate", new object[] {
                                                                                            securityToken,
                                                                                            userId,
                                                                                            dataXML});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginupdateConversionRatesEnddate(string securityToken, long userId, string dataXML, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("updateConversionRatesEnddate", new object[] {
                                                                                     securityToken,
                                                                                     userId,
                                                                                     dataXML}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndupdateConversionRatesEnddate(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateParentReturn")]
        public string updateParent(string securityToken, long userId, string dataXML) 
        {
            object[] results = this.Invoke("updateParent", new object[] {
                                                                            securityToken,
                                                                            userId,
                                                                            dataXML});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginupdateParent(string securityToken, long userId, string dataXML, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("updateParent", new object[] {
                                                                     securityToken,
                                                                     userId,
                                                                     dataXML}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndupdateParent(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("executeActionsReturn")]
        public string executeActions(string securityToken, long userId, long companyId, string dataXML) 
        {
            object[] results = this.Invoke("executeActions", new object[] {
                                                                              securityToken,
                                                                              userId,
                                                                              companyId,
                                                                              dataXML});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginexecuteActions(string securityToken, long userId, long companyId, string dataXML, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("executeActions", new object[] {
                                                                       securityToken,
                                                                       userId,
                                                                       companyId,
                                                                       dataXML}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndexecuteActions(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBoRecordsReturn")]
        public string getBoRecords(string securityToken, long userId, long companyId, long boId) 
        {
            object[] results = this.Invoke("getBoRecords", new object[] {
                                                                            securityToken,
                                                                            userId,
                                                                            companyId,
                                                                            boId});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetBoRecords(string securityToken, long userId, long companyId, long boId, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getBoRecords", new object[] {
                                                                     securityToken,
                                                                     userId,
                                                                     companyId,
                                                                     boId}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetBoRecords(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:BoRecord", ResponseNamespace="urn:BoRecord")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSelectedBoRecordsReturn")]
        public string getSelectedBoRecords(string securityToken, long userId, long companyId, long boId, string Data) 
        {
            object[] results = this.Invoke("getSelectedBoRecords", new object[] {
                                                                                    securityToken,
                                                                                    userId,
                                                                                    companyId,
                                                                                    boId,
                                                                                    Data});
            return ((string)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BegingetSelectedBoRecords(string securityToken, long userId, long companyId, long boId, string Data, System.AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("getSelectedBoRecords", new object[] {
                                                                             securityToken,
                                                                             userId,
                                                                             companyId,
                                                                             boId,
                                                                             Data}, callback, asyncState);
        }
    
        /// <remarks/>
        public string EndgetSelectedBoRecords(System.IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}