//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace Metreos.ClickToTalk.StandaloneClient 
{
    using System;
    using System.Xml.Serialization; 
    
    /// <remarks/>
    [Serializable]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/InitiateCall.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("initiateCall", Namespace="http://metreos.com/InitiateCall.xsd", IsNullable=false)]
    public class initCallType 
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("callee")]
        public calleeType[] callee;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool record;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email;
    }
    
    /// <remarks/>
    [Serializable]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/InitiateCall.xsd")]
    public class calleeType 
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    [Serializable]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/InitiateCallResponse.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("initiateCallResponse", Namespace="http://metreos.com/InitiateCallResponse.xsd", IsNullable=false)]
    public class initCallResponseType 
    {
        
        /// <remarks/>
        public string resultCode;
        
        /// <remarks/>
        public string description;
    }

    [Serializable]
    public class SerializedConfiguration
    {
        public SerializedConfiguration() {} 

        public string   username;

        public string   password;

        public string   email;

        public string   applicationServerIp;
        
        public int      applicationServerPort;

        public bool     alwaysRecord;        
    }
} 
