//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace Metreos.AppArchiveCore.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/AppManifest.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("manifest", Namespace="http://metreos.com/AppManifest.xsd", IsNullable=false)]
    public class manifestType {
        
        /// <remarks/>
        public summaryType summary;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dependency", IsNullable=false)]
        public dependencyType[] dependencies;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("checksum", IsNullable=false)]
        public checksumType[] checksums;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/AppManifest.xsd")]
    public class summaryType {
        
        /// <remarks/>
        public string displayName;

        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string version;
        
        /// <remarks/>
        public string frameworkVersion;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public string company;
        
        /// <remarks/>
        public string author;
        
        /// <remarks/>
        public string copyright;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/AppManifest.xsd")]
    public class checksumType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filename;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/AppManifest.xsd")]
    public class dependencyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dependencyTypes type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/AppManifest.xsd")]
    public enum dependencyTypes {
        
        /// <remarks/>
        provider,
        
        /// <remarks/>
        application,
    }
}
