//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace WebServices.Base.VocalPasswordServer {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VocalPasswordServerSoap", Namespace="http://www.Persay.com/webservices/")]
    public class VocalPasswordServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public VocalPasswordServer() {
            this.Url = "http://10.89.31.17/VocalPassword/VocalPasswordServer.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/Enroll", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnrollStatus Enroll(string speakerId, string speakerSubId, string audio, string configSetName, string enrollAttributes, out int requestId) {
            object[] results = this.Invoke("Enroll", new object[] {
                        speakerId,
                        speakerSubId,
                        audio,
                        configSetName,
                        enrollAttributes});
            requestId = ((int)(results[1]));
            return ((EnrollStatus)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEnroll(string speakerId, string speakerSubId, string audio, string configSetName, string enrollAttributes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Enroll", new object[] {
                        speakerId,
                        speakerSubId,
                        audio,
                        configSetName,
                        enrollAttributes}, callback, asyncState);
        }
        
        /// <remarks/>
        public EnrollStatus EndEnroll(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((EnrollStatus)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/Train", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int Train(string speakerId, string speakerSubId, string configSetName) {
            object[] results = this.Invoke("Train", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTrain(string speakerId, string speakerSubId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Train", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndTrain(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/Verify", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result Verify(string speakerId, string speakerSubId, string audio, string configSetName, out int requestId) {
            object[] results = this.Invoke("Verify", new object[] {
                        speakerId,
                        speakerSubId,
                        audio,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerify(string speakerId, string speakerSubId, string audio, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Verify", new object[] {
                        speakerId,
                        speakerSubId,
                        audio,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result EndVerify(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/VerifyEx", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result VerifyEx(string speakerId, string speakerSubId, string audio, string configSetName, int previousRequestId, out int requestId) {
            object[] results = this.Invoke("VerifyEx", new object[] {
                        speakerId,
                        speakerSubId,
                        audio,
                        configSetName,
                        previousRequestId});
            requestId = ((int)(results[1]));
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerifyEx(string speakerId, string speakerSubId, string audio, string configSetName, int previousRequestId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerifyEx", new object[] {
                        speakerId,
                        speakerSubId,
                        audio,
                        configSetName,
                        previousRequestId}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result EndVerifyEx(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/IdentifySpeakers", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result[] IdentifySpeakers(string[] speakersIds, string speakerSubId, string audio, string configSetName, out int requestId) {
            object[] results = this.Invoke("IdentifySpeakers", new object[] {
                        speakersIds,
                        speakerSubId,
                        audio,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIdentifySpeakers(string[] speakersIds, string speakerSubId, string audio, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IdentifySpeakers", new object[] {
                        speakersIds,
                        speakerSubId,
                        audio,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result[] EndIdentifySpeakers(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/IdentifySpeakersAll", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result[] IdentifySpeakersAll(string[] speakersIds, string audio, string configSetName, out int requestId) {
            object[] results = this.Invoke("IdentifySpeakersAll", new object[] {
                        speakersIds,
                        audio,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIdentifySpeakersAll(string[] speakersIds, string audio, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IdentifySpeakersAll", new object[] {
                        speakersIds,
                        audio,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result[] EndIdentifySpeakersAll(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/IdentifyGroup", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result[] IdentifyGroup(string groupId, string speakerSubId, string audio, string configSetName, out int requestId) {
            object[] results = this.Invoke("IdentifyGroup", new object[] {
                        groupId,
                        speakerSubId,
                        audio,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIdentifyGroup(string groupId, string speakerSubId, string audio, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IdentifyGroup", new object[] {
                        groupId,
                        speakerSubId,
                        audio,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result[] EndIdentifyGroup(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/IdentifyGroupAll", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result[] IdentifyGroupAll(string groupId, string audio, string configSetName, out int requestId) {
            object[] results = this.Invoke("IdentifyGroupAll", new object[] {
                        groupId,
                        audio,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIdentifyGroupAll(string groupId, string audio, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IdentifyGroupAll", new object[] {
                        groupId,
                        audio,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result[] EndIdentifyGroupAll(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((Result[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/IsReadyToTrain", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsReadyToTrain(string speakerId, string speakerSubId, string configSetName, out int requestId) {
            object[] results = this.Invoke("IsReadyToTrain", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsReadyToTrain(string speakerId, string speakerSubId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsReadyToTrain", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsReadyToTrain(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/IsTrained", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsTrained(string speakerId, string speakerSubId, string configSetName, out int requestId) {
            object[] results = this.Invoke("IsTrained", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsTrained(string speakerId, string speakerSubId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsTrained", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsTrained(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/DeleteVoiceprint", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int DeleteVoiceprint(string speakerId, string speakerSubId, string configSetName) {
            object[] results = this.Invoke("DeleteVoiceprint", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteVoiceprint(string speakerId, string speakerSubId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteVoiceprint", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndDeleteVoiceprint(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/DeleteVoiceTemplate", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int DeleteVoiceTemplate(string speakerId, string speakerSubId, string configSetName) {
            object[] results = this.Invoke("DeleteVoiceTemplate", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteVoiceTemplate(string speakerId, string speakerSubId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteVoiceTemplate", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndDeleteVoiceTemplate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/DeleteEnrollSegments", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int DeleteEnrollSegments(string speakerId, string speakerSubId, string configSetName) {
            object[] results = this.Invoke("DeleteEnrollSegments", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteEnrollSegments(string speakerId, string speakerSubId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteEnrollSegments", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndDeleteEnrollSegments(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/RemoveEnrollSegment", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int RemoveEnrollSegment(string speakerId, string speakerSubId, int audioSegmentId, string configSetName) {
            object[] results = this.Invoke("RemoveEnrollSegment", new object[] {
                        speakerId,
                        speakerSubId,
                        audioSegmentId,
                        configSetName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRemoveEnrollSegment(string speakerId, string speakerSubId, int audioSegmentId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RemoveEnrollSegment", new object[] {
                        speakerId,
                        speakerSubId,
                        audioSegmentId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndRemoveEnrollSegment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/GetEnrollSegmentsStatus", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VPEnrollSegmentsStatus GetEnrollSegmentsStatus(string speakerId, string speakerSubId, string configSetName, out int requestId) {
            object[] results = this.Invoke("GetEnrollSegmentsStatus", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName});
            requestId = ((int)(results[1]));
            return ((VPEnrollSegmentsStatus)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEnrollSegmentsStatus(string speakerId, string speakerSubId, string configSetName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEnrollSegmentsStatus", new object[] {
                        speakerId,
                        speakerSubId,
                        configSetName}, callback, asyncState);
        }
        
        /// <remarks/>
        public VPEnrollSegmentsStatus EndGetEnrollSegmentsStatus(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((VPEnrollSegmentsStatus)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/SetExternalRequestId", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int SetExternalRequestId(int internalRequestId, string externalRequestId) {
            object[] results = this.Invoke("SetExternalRequestId", new object[] {
                        internalRequestId,
                        externalRequestId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetExternalRequestId(int internalRequestId, string externalRequestId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetExternalRequestId", new object[] {
                        internalRequestId,
                        externalRequestId}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetExternalRequestId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/GetRequestId", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetRequestId(string externalRequestId, out int requestId) {
            object[] results = this.Invoke("GetRequestId", new object[] {
                        externalRequestId});
            requestId = ((int)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRequestId(string externalRequestId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRequestId", new object[] {
                        externalRequestId}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndGetRequestId(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/GetVerifyDetailedResult", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DetailedResult GetVerifyDetailedResult(int verifyRequestId, out int requestId) {
            object[] results = this.Invoke("GetVerifyDetailedResult", new object[] {
                        verifyRequestId});
            requestId = ((int)(results[1]));
            return ((DetailedResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetVerifyDetailedResult(int verifyRequestId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVerifyDetailedResult", new object[] {
                        verifyRequestId}, callback, asyncState);
        }
        
        /// <remarks/>
        public DetailedResult EndGetVerifyDetailedResult(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((DetailedResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/GetIdentifyDetailedResult", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DetailedResult[] GetIdentifyDetailedResult(int identifyRequestId, out int requestId) {
            object[] results = this.Invoke("GetIdentifyDetailedResult", new object[] {
                        identifyRequestId});
            requestId = ((int)(results[1]));
            return ((DetailedResult[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetIdentifyDetailedResult(int identifyRequestId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetIdentifyDetailedResult", new object[] {
                        identifyRequestId}, callback, asyncState);
        }
        
        /// <remarks/>
        public DetailedResult[] EndGetIdentifyDetailedResult(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((DetailedResult[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/SetApplicationData", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int SetApplicationData(int uniqueId, string title, string data) {
            object[] results = this.Invoke("SetApplicationData", new object[] {
                        uniqueId,
                        title,
                        data});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetApplicationData(int uniqueId, string title, string data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetApplicationData", new object[] {
                        uniqueId,
                        title,
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetApplicationData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/GetApplicationData", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetApplicationData(int uniqueId, string title, out int requestId) {
            object[] results = this.Invoke("GetApplicationData", new object[] {
                        uniqueId,
                        title});
            requestId = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetApplicationData(int uniqueId, string title, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetApplicationData", new object[] {
                        uniqueId,
                        title}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetApplicationData(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/SetVoiceprintData", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int SetVoiceprintData(string speakerId, string speakerSubId, string title, string data) {
            object[] results = this.Invoke("SetVoiceprintData", new object[] {
                        speakerId,
                        speakerSubId,
                        title,
                        data});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetVoiceprintData(string speakerId, string speakerSubId, string title, string data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetVoiceprintData", new object[] {
                        speakerId,
                        speakerSubId,
                        title,
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetVoiceprintData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/GetVoiceprintData", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVoiceprintData(string speakerId, string speakerSubId, string title, out int requestId) {
            object[] results = this.Invoke("GetVoiceprintData", new object[] {
                        speakerId,
                        speakerSubId,
                        title});
            requestId = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetVoiceprintData(string speakerId, string speakerSubId, string title, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVoiceprintData", new object[] {
                        speakerId,
                        speakerSubId,
                        title}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetVoiceprintData(System.IAsyncResult asyncResult, out int requestId) {
            object[] results = this.EndInvoke(asyncResult);
            requestId = ((int)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Persay.com/webservices/SetAuthenticity", RequestNamespace="http://www.Persay.com/webservices/", ResponseNamespace="http://www.Persay.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestId")]
        public int SetAuthenticity(int verifyRequestId, Authentication authenticity) {
            object[] results = this.Invoke("SetAuthenticity", new object[] {
                        verifyRequestId,
                        authenticity});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetAuthenticity(int verifyRequestId, Authentication authenticity, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetAuthenticity", new object[] {
                        verifyRequestId,
                        authenticity}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetAuthenticity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public enum EnrollStatus {
        
        /// <remarks/>
        NotReady,
        
        /// <remarks/>
        Ready,
        
        /// <remarks/>
        Trained,
        
        /// <remarks/>
        TrainFailed,
        
        /// <remarks/>
        Full,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public class Result {
        
        /// <remarks/>
        public string SpeakerId;
        
        /// <remarks/>
        public string SpeakerSubId;
        
        /// <remarks/>
        public Decision Decision;
        
        /// <remarks/>
        public DecisionReason DecisionReason;
        
        /// <remarks/>
        public int Score;
        
        /// <remarks/>
        public int RawScore;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public enum Decision {
        
        /// <remarks/>
        Match,
        
        /// <remarks/>
        Mismatch,
        
        /// <remarks/>
        Inconclusive,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public enum DecisionReason {
        
        /// <remarks/>
        VoiceprintMatch,
        
        /// <remarks/>
        VoiceprintMismatch,
        
        /// <remarks/>
        VoiceprintInconclusive,
        
        /// <remarks/>
        VoiceprintPartialMatch,
        
        /// <remarks/>
        AudioTooShort,
        
        /// <remarks/>
        AudioTooLong,
        
        /// <remarks/>
        WrongPassphrase,
        
        /// <remarks/>
        PlaybackIndication,
        
        /// <remarks/>
        InternalError,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public class IntermediateResult {
        
        /// <remarks/>
        public int Score;
        
        /// <remarks/>
        public int RawScore;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public class DetailedResult {
        
        /// <remarks/>
        public Result Result;
        
        /// <remarks/>
        public IntermediateResult[] IntermediateResult;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public class VPEnrollSegmentsStatus {
        
        /// <remarks/>
        public int MissingSegments;
        
        /// <remarks/>
        public EnrollStatus Status;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Persay.com/webservices/")]
    public enum Authentication {
        
        /// <remarks/>
        Authentic,
        
        /// <remarks/>
        Impostor,
    }
}
