//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace WebServices.NativeTypes.VocalPasswordServer
{
    using System;
    using WebServices.Base.VocalPasswordServer;
    
    [Serializable()]
    public class EnrollStatusType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.EnrollStatus inner;
        public EnrollStatusType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.EnrollStatus Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.EnrollStatus();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.EnrollStatus incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class ResultType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.Result inner;
        public ResultType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.Result Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.Result();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.Result incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class DecisionType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.Decision inner;
        public DecisionType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.Decision Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.Decision();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.Decision incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class DecisionReasonType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.DecisionReason inner;
        public DecisionReasonType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.DecisionReason Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.DecisionReason();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.DecisionReason incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class IntermediateResultType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.IntermediateResult inner;
        public IntermediateResultType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.IntermediateResult Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.IntermediateResult();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.IntermediateResult incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class DetailedResultType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.DetailedResult inner;
        public DetailedResultType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.DetailedResult Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.DetailedResult();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.DetailedResult incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class VPEnrollSegmentsStatusType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.VPEnrollSegmentsStatus inner;
        public VPEnrollSegmentsStatusType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.VPEnrollSegmentsStatus Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.VPEnrollSegmentsStatus();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.VPEnrollSegmentsStatus incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class AuthenticationType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.Authentication inner;
        public AuthenticationType()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.Authentication Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.VocalPasswordServer.Authentication();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.Authentication incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class ResultArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.Result[] inner;
        public ResultArray()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.Result[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.Result[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class DetailedResultArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.VocalPasswordServer.DetailedResult[] inner;
        public DetailedResultArray()
        {
            Reset();
        }
        public virtual WebServices.Base.VocalPasswordServer.DetailedResult[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.VocalPasswordServer.DetailedResult[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
}
