//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Metreos.Types.Presence.Pidf
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    [System.Xml.Serialization.XmlRootAttribute("servcaps", Namespace="urn:ietf:params:xml:ns:pidf:caps", IsNullable=false)]
    public partial class servcapstype
    {

        private actortype actorField;

        private bool applicationField;

        private bool applicationFieldSpecified;

        private bool audioField;

        private bool audioFieldSpecified;

        private bool automataField;

        private bool automataFieldSpecified;

        private classtype classField;

        private bool controlField;

        private bool controlFieldSpecified;

        private bool dataField;

        private bool dataFieldSpecified;

        private string descriptionField;

        private duplextype duplexField;

        private eventpackagestype eventpackagesField;

        private extensionstype extensionsField;

        private bool isfocusField;

        private bool isfocusFieldSpecified;

        private bool messageField;

        private bool messageFieldSpecified;

        private methodstype methodsField;

        private languagestype languagesField;

        private prioritytype priorityField;

        private schemestype schemesField;

        private bool textField;

        private bool textFieldSpecified;

        private string[] typeField;

        private bool videoField;

        private bool videoFieldSpecified;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public actortype actor
        {
            get
            {
                return this.actorField;
            }
            set
            {
                this.actorField = value;
            }
        }

        /// <remarks/>
        public bool application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool applicationSpecified
        {
            get
            {
                return this.applicationFieldSpecified;
            }
            set
            {
                this.applicationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool audio
        {
            get
            {
                return this.audioField;
            }
            set
            {
                this.audioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool audioSpecified
        {
            get
            {
                return this.audioFieldSpecified;
            }
            set
            {
                this.audioFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool automata
        {
            get
            {
                return this.automataField;
            }
            set
            {
                this.automataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool automataSpecified
        {
            get
            {
                return this.automataFieldSpecified;
            }
            set
            {
                this.automataFieldSpecified = value;
            }
        }

        /// <remarks/>
        public classtype @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <remarks/>
        public bool control
        {
            get
            {
                return this.controlField;
            }
            set
            {
                this.controlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool controlSpecified
        {
            get
            {
                return this.controlFieldSpecified;
            }
            set
            {
                this.controlFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSpecified
        {
            get
            {
                return this.dataFieldSpecified;
            }
            set
            {
                this.dataFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public duplextype duplex
        {
            get
            {
                return this.duplexField;
            }
            set
            {
                this.duplexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event-packages")]
        public eventpackagestype eventpackages
        {
            get
            {
                return this.eventpackagesField;
            }
            set
            {
                this.eventpackagesField = value;
            }
        }

        /// <remarks/>
        public extensionstype extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }

        /// <remarks/>
        public bool isfocus
        {
            get
            {
                return this.isfocusField;
            }
            set
            {
                this.isfocusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isfocusSpecified
        {
            get
            {
                return this.isfocusFieldSpecified;
            }
            set
            {
                this.isfocusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageSpecified
        {
            get
            {
                return this.messageFieldSpecified;
            }
            set
            {
                this.messageFieldSpecified = value;
            }
        }

        /// <remarks/>
        public methodstype methods
        {
            get
            {
                return this.methodsField;
            }
            set
            {
                this.methodsField = value;
            }
        }

        /// <remarks/>
        public languagestype languages
        {
            get
            {
                return this.languagesField;
            }
            set
            {
                this.languagesField = value;
            }
        }

        /// <remarks/>
        public prioritytype priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        public schemestype schemes
        {
            get
            {
                return this.schemesField;
            }
            set
            {
                this.schemesField = value;
            }
        }

        /// <remarks/>
        public bool text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool textSpecified
        {
            get
            {
                return this.textFieldSpecified;
            }
            set
            {
                this.textFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public string[] type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public bool video
        {
            get
            {
                return this.videoField;
            }
            set
            {
                this.videoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool videoSpecified
        {
            get
            {
                return this.videoFieldSpecified;
            }
            set
            {
                this.videoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class actortype
    {

        private actortypes supportedField;

        private actortypes notsupportedField;

        /// <remarks/>
        public actortypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public actortypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class actortypes
    {

        private string attendantField;

        private string informationField;

        private string msgtakerField;

        private string principalField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public string attendant
        {
            get
            {
                return this.attendantField;
            }
            set
            {
                this.attendantField = value;
            }
        }

        /// <remarks/>
        public string information
        {
            get
            {
                return this.informationField;
            }
            set
            {
                this.informationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msg-taker")]
        public string msgtaker
        {
            get
            {
                return this.msgtakerField;
            }
            set
            {
                this.msgtakerField = value;
            }
        }

        /// <remarks/>
        public string principal
        {
            get
            {
                return this.principalField;
            }
            set
            {
                this.principalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class mobilitytypes
    {

        private string fixedField;

        private string mobileField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public string @fixed
        {
            get
            {
                return this.fixedField;
            }
            set
            {
                this.fixedField = value;
            }
        }

        /// <remarks/>
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class mobilitytype
    {

        private mobilitytypes supportedField;

        private mobilitytypes notsupportedField;

        /// <remarks/>
        public mobilitytypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public mobilitytypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class schemestype
    {

        private string[] supportedField;

        private string[] notsupportedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("s", IsNullable=false)]
        public string[] supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("s", IsNullable=false)]
        public string[] notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class rangetype
    {

        private string minvalueField;

        private string maxvalueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minvalue
        {
            get
            {
                return this.minvalueField;
            }
            set
            {
                this.minvalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxvalue
        {
            get
            {
                return this.maxvalueField;
            }
            set
            {
                this.maxvalueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class lowerthantype
    {

        private string maxvalueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxvalue
        {
            get
            {
                return this.maxvalueField;
            }
            set
            {
                this.maxvalueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class higherthantype
    {

        private string minvalueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minvalue
        {
            get
            {
                return this.minvalueField;
            }
            set
            {
                this.minvalueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class equalstype
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class prioritytypes
    {

        private equalstype[] equalsField;

        private higherthantype[] higherhanField;

        private lowerthantype[] lowerthanField;

        private rangetype[] rangeField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("equals")]
        public equalstype[] equals
        {
            get
            {
                return this.equalsField;
            }
            set
            {
                this.equalsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("higherhan")]
        public higherthantype[] higherhan
        {
            get
            {
                return this.higherhanField;
            }
            set
            {
                this.higherhanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lowerthan")]
        public lowerthantype[] lowerthan
        {
            get
            {
                return this.lowerthanField;
            }
            set
            {
                this.lowerthanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("range")]
        public rangetype[] range
        {
            get
            {
                return this.rangeField;
            }
            set
            {
                this.rangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class prioritytype
    {

        private prioritytypes supportedField;

        private prioritytypes notsupportedField;

        /// <remarks/>
        public prioritytypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public prioritytypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class languagestype
    {

        private string[] supportedField;

        private string[] notsupportedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("l", IsNullable=false)]
        public string[] supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("l", IsNullable=false)]
        public string[] notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class methodtypes
    {

        private string aCKField;

        private string bYEField;

        private string cANCELField;

        private string iNFOField;

        private string iNVITEField;

        private string mESSAGEField;

        private string nOTIFYField;

        private string oPTIONSField;

        private string pRACKField;

        private string pUBLISHField;

        private string rEFERField;

        private string rEGISTERField;

        private string sUBSCRIBEField;

        private string uPDATEField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public string ACK
        {
            get
            {
                return this.aCKField;
            }
            set
            {
                this.aCKField = value;
            }
        }

        /// <remarks/>
        public string BYE
        {
            get
            {
                return this.bYEField;
            }
            set
            {
                this.bYEField = value;
            }
        }

        /// <remarks/>
        public string CANCEL
        {
            get
            {
                return this.cANCELField;
            }
            set
            {
                this.cANCELField = value;
            }
        }

        /// <remarks/>
        public string INFO
        {
            get
            {
                return this.iNFOField;
            }
            set
            {
                this.iNFOField = value;
            }
        }

        /// <remarks/>
        public string INVITE
        {
            get
            {
                return this.iNVITEField;
            }
            set
            {
                this.iNVITEField = value;
            }
        }

        /// <remarks/>
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }

        /// <remarks/>
        public string NOTIFY
        {
            get
            {
                return this.nOTIFYField;
            }
            set
            {
                this.nOTIFYField = value;
            }
        }

        /// <remarks/>
        public string OPTIONS
        {
            get
            {
                return this.oPTIONSField;
            }
            set
            {
                this.oPTIONSField = value;
            }
        }

        /// <remarks/>
        public string PRACK
        {
            get
            {
                return this.pRACKField;
            }
            set
            {
                this.pRACKField = value;
            }
        }

        /// <remarks/>
        public string PUBLISH
        {
            get
            {
                return this.pUBLISHField;
            }
            set
            {
                this.pUBLISHField = value;
            }
        }

        /// <remarks/>
        public string REFER
        {
            get
            {
                return this.rEFERField;
            }
            set
            {
                this.rEFERField = value;
            }
        }

        /// <remarks/>
        public string REGISTER
        {
            get
            {
                return this.rEGISTERField;
            }
            set
            {
                this.rEGISTERField = value;
            }
        }

        /// <remarks/>
        public string SUBSCRIBE
        {
            get
            {
                return this.sUBSCRIBEField;
            }
            set
            {
                this.sUBSCRIBEField = value;
            }
        }

        /// <remarks/>
        public string UPDATE
        {
            get
            {
                return this.uPDATEField;
            }
            set
            {
                this.uPDATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class methodstype
    {

        private methodtypes supportedField;

        private methodtypes notsupportedField;

        /// <remarks/>
        public methodtypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public methodtypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class extensiontypes
    {

        private string joinField;

        private string pathField;

        private string preconditionField;

        private string prefField;

        private string privacyField;

        private string rel100Field;

        private string replacesField;

        private string secagreeField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public string join
        {
            get
            {
                return this.joinField;
            }
            set
            {
                this.joinField = value;
            }
        }

        /// <remarks/>
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public string precondition
        {
            get
            {
                return this.preconditionField;
            }
            set
            {
                this.preconditionField = value;
            }
        }

        /// <remarks/>
        public string pref
        {
            get
            {
                return this.prefField;
            }
            set
            {
                this.prefField = value;
            }
        }

        /// <remarks/>
        public string privacy
        {
            get
            {
                return this.privacyField;
            }
            set
            {
                this.privacyField = value;
            }
        }

        /// <remarks/>
        public string rel100
        {
            get
            {
                return this.rel100Field;
            }
            set
            {
                this.rel100Field = value;
            }
        }

        /// <remarks/>
        public string replaces
        {
            get
            {
                return this.replacesField;
            }
            set
            {
                this.replacesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sec-agree")]
        public string secagree
        {
            get
            {
                return this.secagreeField;
            }
            set
            {
                this.secagreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class extensionstype
    {

        private extensiontypes supportedField;

        private extensiontypes notsupportedField;

        /// <remarks/>
        public extensiontypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public extensiontypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class eventtypes
    {

        private string messagesummaryField;

        private string presenceField;

        private string referField;

        private string regField;

        private string siemensRTPStatsField;

        private string spiritsINDPsField;

        private string spiritsuserprofField;

        private string winfoField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-summary")]
        public string messagesummary
        {
            get
            {
                return this.messagesummaryField;
            }
            set
            {
                this.messagesummaryField = value;
            }
        }

        /// <remarks/>
        public string presence
        {
            get
            {
                return this.presenceField;
            }
            set
            {
                this.presenceField = value;
            }
        }

        /// <remarks/>
        public string refer
        {
            get
            {
                return this.referField;
            }
            set
            {
                this.referField = value;
            }
        }

        /// <remarks/>
        public string reg
        {
            get
            {
                return this.regField;
            }
            set
            {
                this.regField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Siemens-RTP-Stats")]
        public string SiemensRTPStats
        {
            get
            {
                return this.siemensRTPStatsField;
            }
            set
            {
                this.siemensRTPStatsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("spirits-INDPs")]
        public string spiritsINDPs
        {
            get
            {
                return this.spiritsINDPsField;
            }
            set
            {
                this.spiritsINDPsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("spirits-user-prof")]
        public string spiritsuserprof
        {
            get
            {
                return this.spiritsuserprofField;
            }
            set
            {
                this.spiritsuserprofField = value;
            }
        }

        /// <remarks/>
        public string winfo
        {
            get
            {
                return this.winfoField;
            }
            set
            {
                this.winfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="event-packagestype", Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class eventpackagestype
    {

        private eventtypes supportedField;

        private eventtypes notsupportedField;

        /// <remarks/>
        public eventtypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public eventtypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class duplextypes
    {

        private string fullField;

        private string halfField;

        private string receiveonlyField;

        private string sendonlyField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public string full
        {
            get
            {
                return this.fullField;
            }
            set
            {
                this.fullField = value;
            }
        }

        /// <remarks/>
        public string half
        {
            get
            {
                return this.halfField;
            }
            set
            {
                this.halfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receive-only")]
        public string receiveonly
        {
            get
            {
                return this.receiveonlyField;
            }
            set
            {
                this.receiveonlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("send-only")]
        public string sendonly
        {
            get
            {
                return this.sendonlyField;
            }
            set
            {
                this.sendonlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class duplextype
    {

        private duplextypes supportedField;

        private duplextypes notsupportedField;

        /// <remarks/>
        public duplextypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public duplextypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class classtypes
    {

        private string businessField;

        private string personalField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public string business
        {
            get
            {
                return this.businessField;
            }
            set
            {
                this.businessField = value;
            }
        }

        /// <remarks/>
        public string personal
        {
            get
            {
                return this.personalField;
            }
            set
            {
                this.personalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    public partial class classtype
    {

        private classtypes supportedField;

        private classtypes notsupportedField;

        /// <remarks/>
        public classtypes supported
        {
            get
            {
                return this.supportedField;
            }
            set
            {
                this.supportedField = value;
            }
        }

        /// <remarks/>
        public classtypes notsupported
        {
            get
            {
                return this.notsupportedField;
            }
            set
            {
                this.notsupportedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:pidf:caps", IsNullable=false)]
    public partial class devcaps
    {

        private string descriptionField;

        private mobilitytype mobilityField;

        private prioritytype priorityField;

        private System.Xml.XmlElement[] anyField;

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public mobilitytype mobility
        {
            get
            {
                return this.mobilityField;
            }
            set
            {
                this.mobilityField = value;
            }
        }

        /// <remarks/>
        public prioritytype priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

}//namespace