/**************************************************************
    Copyright (C) 2000-2002.  Intel Corporation.
 
    All Rights Reserved.  All names, products,
    and services mentioned herein are the trademarks
    or registered trademarks of their respective organizations
    and are the sole property of their respective owners.
 **************************************************************/
 
/*
*    AUTO-VERSIONING HEADER  DO NOT HAND MODIFY
*    ===================================================================
*    %name:          %
*    %version:       %
*    %instance:      %
*    %created_by:    %
*    %date_modified: %
*    ===================================================================
*/

/*
        dlg_datautils_msgids.h - This file contains all
        errors generated by the Data Utilities Library
				This library generates only internal errors
*/

#ifndef _DLG_DATAUTILS_MSGIDS_H
#define _DLG_DATAUTILS_MSGIDS_H

#include "dlgfacil.h"

/*  
		FOR EXTERNAL USE
    Data Utilities Library Message  Definition 
		for use by clients
*/

  
/*  FOR INTERNAL USE ONLY.
    Data Utilities Library Message  Definition 
    For use by dialogic not for client use.
*/

const DlgSysResultType DLG_DB_INTERNAL_ERROR=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000000);

const DlgSysResultType DLG_DB_SYSTEM_ERROR=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000001);

const DlgSysResultType DLG_DATABASE_OPEN=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000002);

const DlgSysResultType DLG_DATABASE_UNAVAIL=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000003);

const DlgSysResultType DLG_INVALID_USERID=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000004);

const DlgSysResultType DLG_INVALID_NAMELEN=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000005);

const DlgSysResultType DLG_INVALID_LOCKMGR=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000006);

const DlgSysResultType DLG_TRANSACTION_ACTIVE=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000007);

const DlgSysResultType DLG_TRANSACTION_NOTACTIVE=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000008);

const DlgSysResultType DLG_INVALID_TRANSACTIONID=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000009);

const DlgSysResultType DLG_INVALID_SET=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000010);

const DlgSysResultType DLG_CURRENCY_ERROR=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000011);

const DlgSysResultType DLG_NO_LOCK=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000012);

const DlgSysResultType DLG_LOCK_NOT_FREE=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000013);

const DlgSysResultType DLG_INVALID_MEMBER=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000014);

const DlgSysResultType DLG_INVALID_OWNER=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000015);

const DlgSysResultType DLG_INVALID_RECORD=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000016);

const DlgSysResultType DLG_INVALID_FIELD=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000017);

const DlgSysResultType DLG_KEY_ERROR=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000018);

const DlgSysResultType DLG_NOT_KEY=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000019);

const DlgSysResultType DLG_INVALID_DICTIONARY=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000020);

const DlgSysResultType DLG_ILLEGAL_OPERATION=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000021);

const DlgSysResultType DLG_BAD_PATH=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000022);

const DlgSysResultType DLG_INVALID_TASK=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000023);

const DlgSysResultType DLG_DATABASE_NOT_CLOSED=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000024);

const DlgSysResultType DLG_INVALID_DATABASE=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000025);

const DlgSysResultType DLG_NO_MEMORY=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000026);

const DlgSysResultType DLG_INVALID_DB_ACCESS=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000027);

const DlgSysResultType DLG_RECOVERY_ACTIVE=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000028);

const DlgSysResultType DLG_FAILED_DB_OPEN=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000029);

const DlgSysResultType DLG_FAILED_DB_CLOSE=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000030);

const DlgSysResultType DLG_FAILED_DB_LOCK=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000031);

const DlgSysResultType DLG_REC_NOT_FOUND=
( DLG_ERROR_CODE | DLG_DATAUTILS_FACILITY | 0x00000032);

const DlgSysResultType DLG_END_OF_SET=
( DLG_INFO_CODE | DLG_DATAUTILS_FACILITY | 0x00000033);

#endif
