/**************************************************************
    Copyright (C) 2000-2002.  Intel Corporation.
 
    All Rights Reserved.  All names, products,
    and services mentioned herein are the trademarks
    or registered trademarks of their respective organizations
    and are the sole property of their respective owners.
 **************************************************************/
 
/*
*    AUTO-VERSIONING HEADER  DO NOT HAND MODIFY
*    ===================================================================
*    %name:          %
*    %version:       %
*    %instance:      %
*    %created_by:    %
*    %date_modified: %
*    ===================================================================
*/

/*
        dlg_dataengine_msgids.h - This file contains all
        errors generated by the Data Engine Library
*/

#ifndef _DLG_DATAENGINE_MSGIDS_H
#define _DLG_DATAENGINE_MSGIDS_H

#include "dlgfacil.h"

/*  
		FOR EXTERNAL USE
    Data Utilities Library Message  Definition 
		for use by clients
*/

  
/*  FOR INTERNAL USE ONLY.
    Data Utilities Library Message  Definition 
    For use by dialogic not for client use.
*/

const DlgSysResultType DLG_DUPLICATE_SERIAL_NUMBER=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000000);

const DlgSysResultType DLG_INVALID_NODEID=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000001);

const DlgSysResultType DLG_INVALID_BOARDAUID=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000002);

const DlgSysResultType DLG_INVALID_CLOCKAGENTID=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000003);

const DlgSysResultType DLG_INVALID_BUSID=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000004);

const DlgSysResultType DLG_INVALID_TECH=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000005);

const DlgSysResultType DLG_DATA_NOT_FOUND=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000006);

const DlgSysResultType DLG_FAILED_DATA_ADD=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000007);

const DlgSysResultType DLG_FAILED_DATA_UPDATE=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000008);

const DlgSysResultType DLG_FAILED_DATA_DELETE=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000009);

const DlgSysResultType DLG_INVALID_TSCLAIMID=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000010);

const DlgSysResultType DLG_INVALID_DBPARAM=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000011);

const DlgSysResultType DLG_TS_PARTIAL_ERROR=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000012);

const DlgSysResultType DLG_DUPLICATE_TIMESLOTS=
( DLG_ERROR_CODE | DLG_DATAENGINE_FACILITY | 0x00000013);

#endif
