/*****************************************************************************
 * Copyright © 1991-1996, Intel Corporation. All rights reserved.  Intel is a 
 * trademark or registered trademark of Intel Corporation or its subsidiaries 
 * in the United States and other countries. Other names and brands may be 
 * claimed as the property of others. 
 *****************************************************************************/
 /***********************************************************************
 *        FILE: dxsync.h
 * DESCRIPTION: Header File for DIALOGIC Windows NT library
 **********************************************************************/

#ifndef __DXSYNC_H__
#define __DXSYNC_H__

#ifdef __STANDALONE__            /* List of required header files */
#endif


/*
 * SYNC/ASYNC operation flags
 */
#define EV_ASYNC              0x8000
#define EV_SYNC               0x0000


#endif


