/***********************************************************************
 *        FILE: dxsync.h
 * DESCRIPTION: Header File for DIALOGIC Windows NT library
 *
 *   Copyright (c) 1991-1996 Dialogic Corp. All Rights Reserved
 *
 *   THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Dialogic Corp.
 *   The copyright notice above does not evidence any actual or
 *   intended publication of such source code.
 **********************************************************************/

#ifndef __DXSYNC_H__
#define __DXSYNC_H__

#ifdef __STANDALONE__            /* List of required header files */
#endif


/*
 * SYNC/ASYNC operation flags
 */
#define EV_ASYNC              0x8000
#define EV_SYNC               0x0000


#endif


