//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace WebServices.NativeTypes.JiraSoapServiceService
{
    using System;
    using WebServices.Base.JiraSoapServiceService;
    
    [Serializable()]
    public class RemoteEntityType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteEntity inner;
        public RemoteEntityType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteEntity Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteEntity();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteEntity incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteUserType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteUser inner;
        public RemoteUserType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteUser Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteUser();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteUser incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteConfigurationType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteConfiguration inner;
        public RemoteConfigurationType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteConfiguration Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteConfiguration();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteConfiguration incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteFieldValueType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteFieldValue inner;
        public RemoteFieldValueType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteFieldValue Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteFieldValue();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteFieldValue incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteCustomFieldValueType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteCustomFieldValue inner;
        public RemoteCustomFieldValueType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteCustomFieldValue Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteCustomFieldValue();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteCustomFieldValue incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemotePermissionType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemotePermission inner;
        public RemotePermissionType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemotePermission Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemotePermission();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemotePermission incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemotePermissionMappingType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemotePermissionMapping inner;
        public RemotePermissionMappingType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemotePermissionMapping Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemotePermissionMapping();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemotePermissionMapping incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteSchemeType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteScheme inner;
        public RemoteSchemeType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteScheme Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteScheme();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteScheme incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemotePermissionSchemeType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemotePermissionScheme inner;
        public RemotePermissionSchemeType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemotePermissionScheme Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemotePermissionScheme();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemotePermissionScheme incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class AbstractRemoteEntityType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.AbstractRemoteEntity inner;
        public AbstractRemoteEntityType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.AbstractRemoteEntity Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.AbstractRemoteEntity incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteIssueType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteIssue inner;
        public RemoteIssueType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteIssue Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteIssue();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteIssue incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class AbstractNamedRemoteEntityType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.AbstractNamedRemoteEntity inner;
        public AbstractNamedRemoteEntityType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.AbstractNamedRemoteEntity Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.AbstractNamedRemoteEntity incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteVersionType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteVersion inner;
        public RemoteVersionType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteVersion Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteVersion();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteVersion incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteFilterType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteFilter inner;
        public RemoteFilterType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteFilter Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteFilter();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteFilter incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteFieldType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteField inner;
        public RemoteFieldType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteField Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteField();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteField incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteProjectType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteProject inner;
        public RemoteProjectType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteProject Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteProject();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteProject incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteNamedObjectType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteNamedObject inner;
        public RemoteNamedObjectType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteNamedObject Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteNamedObject();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteNamedObject incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class AbstractRemoteConstantType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.AbstractRemoteConstant inner;
        public AbstractRemoteConstantType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.AbstractRemoteConstant Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.AbstractRemoteConstant incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteResolutionType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteResolution inner;
        public RemoteResolutionType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteResolution Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteResolution();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteResolution incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemotePriorityType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemotePriority inner;
        public RemotePriorityType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemotePriority Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemotePriority();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemotePriority incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteIssueTypeType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteIssueType inner;
        public RemoteIssueTypeType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteIssueType Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteIssueType();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteIssueType incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteStatusType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteStatus inner;
        public RemoteStatusType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteStatus Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteStatus();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteStatus incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteComponentType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteComponent inner;
        public RemoteComponentType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteComponent Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteComponent();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteComponent incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteCommentType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteComment inner;
        public RemoteCommentType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteComment Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteComment();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteComment incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteServerInfoType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteServerInfo inner;
        public RemoteServerInfoType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteServerInfo Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteServerInfo();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteServerInfo incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteGroupType : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteGroup inner;
        public RemoteGroupType()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteGroup Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = new WebServices.Base.JiraSoapServiceService.RemoteGroup();
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteGroup incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteCommentArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteComment[] inner;
        public RemoteCommentArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteComment[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteComment[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteComponentArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteComponent[] inner;
        public RemoteComponentArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteComponent[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteComponent[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteStatusArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteStatus[] inner;
        public RemoteStatusArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteStatus[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteStatus[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteNamedObjectArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteNamedObject[] inner;
        public RemoteNamedObjectArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteNamedObject[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteNamedObject[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteProjectArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteProject[] inner;
        public RemoteProjectArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteProject[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteProject[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteIssueTypeArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteIssueType[] inner;
        public RemoteIssueTypeArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteIssueType[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteIssueType[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemotePriorityArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemotePriority[] inner;
        public RemotePriorityArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemotePriority[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemotePriority[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteResolutionArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteResolution[] inner;
        public RemoteResolutionArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteResolution[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteResolution[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteFieldArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteField[] inner;
        public RemoteFieldArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteField[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteField[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteFilterArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteFilter[] inner;
        public RemoteFilterArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteFilter[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteFilter[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteVersionArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteVersion[] inner;
        public RemoteVersionArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteVersion[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteVersion[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteSchemeArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteScheme[] inner;
        public RemoteSchemeArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteScheme[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteScheme[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemotePermissionSchemeArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemotePermissionScheme[] inner;
        public RemotePermissionSchemeArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemotePermissionScheme[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemotePermissionScheme[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemotePermissionArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemotePermission[] inner;
        public RemotePermissionArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemotePermission[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemotePermission[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
    [Serializable()]
    public class RemoteIssueArray : Metreos.ApplicationFramework.IVariable
    {
        private WebServices.Base.JiraSoapServiceService.RemoteIssue[] inner;
        public RemoteIssueArray()
        {
            Reset();
        }
        public virtual WebServices.Base.JiraSoapServiceService.RemoteIssue[] Value
        {
            get
            {
                return inner;
            }
            set
            {
                inner = value;
            }
        }
        /// IVariable interface
        public virtual void Reset()
        {
            inner = null;
        }
        /// IVariable interface
        public virtual bool Parse(string incomingValue)
        {
            return true;
        }
        public virtual bool Parse(WebServices.Base.JiraSoapServiceService.RemoteIssue[] incomingValue)
        {
            inner = incomingValue;
            return true;
        }
    }
}
