//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace ChatServer 
{
  using System;
  using RemObjects.SDK;
  using RemObjects.SDK.Types;
  using RemObjects.SDK.Server;
    
  [RemObjects.SDK.Server.Invoker()]
  public class ChatService_Invoker : RemObjects.SDK.Server.Invoker 
  {
    public ChatService_Invoker() : 
      base() 
    {
    }
    public static void Invoke_Enter(RemObjects.SDK.IROService __Instance, RemObjects.SDK.IMessage __Message, RemObjects.SDK.Server.IServerChannelInfo __ServerChannelInfo, out RemObjects.SDK.Server.ResponseOptions __oResponseOptions) 
    {
      string aUsername = __Message.ReadAnsiString("aUsername");
      string aPassword = __Message.ReadAnsiString("aPassword");
      ((IChatService)(__Instance)).Enter(aUsername, aPassword);
      __Message.InitializeMessage(__ServerChannelInfo, "ChatService", "Enter");
      __Message.FinalizeMessage();
      __oResponseOptions = RemObjects.SDK.Server.ResponseOptions.roNoResponse;
    }
    public static void Invoke_Leave(RemObjects.SDK.IROService __Instance, RemObjects.SDK.IMessage __Message, RemObjects.SDK.Server.IServerChannelInfo __ServerChannelInfo, out RemObjects.SDK.Server.ResponseOptions __oResponseOptions) 
    {
      ((IChatService)(__Instance)).Leave();
      __Message.InitializeMessage(__ServerChannelInfo, "ChatService", "Leave");
      __Message.FinalizeMessage();
      __oResponseOptions = RemObjects.SDK.Server.ResponseOptions.roNoResponse;
    }
    public static void Invoke_SendMessage(RemObjects.SDK.IROService __Instance, RemObjects.SDK.IMessage __Message, RemObjects.SDK.Server.IServerChannelInfo __ServerChannelInfo, out RemObjects.SDK.Server.ResponseOptions __oResponseOptions) 
    {
      string aMessage = __Message.ReadAnsiString("aMessage");
      ((IChatService)(__Instance)).SendMessage(aMessage);
      __Message.InitializeMessage(__ServerChannelInfo, "ChatService", "SendMessage");
      __Message.FinalizeMessage();
      __oResponseOptions = RemObjects.SDK.Server.ResponseOptions.roNoResponse;
    }
  }
}
