//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace Metreos.Max.Framework.Satellite.Property {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Properties.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Defaults.xmlEltProperties, Namespace="http://tempuri.org/Properties.xsd", IsNullable=false)]
    public class PropertiesType {
        
        /// <remarks/>  
        [System.Xml.Serialization.XmlElementAttribute("p")]
        public SimplePropertyType[] Property;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Properties.xsd")]
    public class SimplePropertyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("s")]
        public SimplePropertyType[] ChildrenProperties;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("n")]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("v")]
        public string Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("i")]
        public string Identifier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("c")]
        public string Category;
    }
}
