//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace Metreos.Types.ClickToTalk.Schemas {
    using System.Xml.Serialization;
    using System;
    
    
    [Serializable]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://metreos.com/InitiateCallResponse.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("initiateCallResponse", Namespace="http://metreos.com/InitiateCallResponse.xsd", IsNullable=false)]
    public class initCallResponseType {
        
        /// <remarks/>
        public string resultCode;
        
        /// <remarks/>
        public string description;
    }
}
